# Generated by Django 4.1.7 on 2023-04-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_post_description_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='slug',
        ),
    ]
