# Generated by Django 4.1.7 on 2023-04-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_url_category_slug_rename_url_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
