# Generated by Django 4.1.7 on 2023-04-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('programming Languages', 'Programming Languages'), ('food', 'Food'), ('ipl', 'IPL')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(choices=[('c lanuage', 'C LANGUAGE'), ('c++', 'C++'), ('python', 'PYTHON'), ('java', 'JAVA'), ('western food', 'WESTERN FOOD'), ('indian', 'INDIAN')], max_length=50, null=True),
        ),
    ]
